name: test-gh

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.16"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      run: |
        set -e -x

        export GOPATH=$(echo `pwd`)
        export PATH="$PATH:$GOPATH/bin"
        cd src/github.com/${{ github.repository }}

        # deploy local registry and run tests
        ./hack/test-all-local-registry.sh

  test-harbor:
    name: Test GH with Harbor
    runs-on: ubuntu-latest
    environment: TanzuNet Registry Dev e2e
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.16"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      env:
        IMGPKG_E2E_IMAGE: "dev.registry.pivotal.io/imgpkg/github-action-test-relocation"
        IMGPKG_E2E_RELOCATION_REPO: "dev.registry.pivotal.io/imgpkg/github-action-imgpkg-test"
        TanzuNetDevUsername: ${{ secrets.TanzuNetDevUsername }}
        TanzuNetDevPassword: ${{ secrets.TanzuNetDevPassword }}
      run: |
        set -e

        # Prevent conflicts from multiple e2e tests run in parallel from diff PR's
        export IMGPKG_E2E_IMAGE="$IMGPKG_E2E_IMAGE-$GITHUB_RUN_ID"
        export IMGPKG_E2E_RELOCATION_REPO="$IMGPKG_E2E_RELOCATION_REPO-$GITHUB_RUN_ID"

        export GOPATH=$(echo `pwd`)
        export PATH="$PATH:$GOPATH/bin"
        cd src/github.com/${{ github.repository }}

        docker login dev.registry.pivotal.io -u "$TanzuNetDevUsername" -p "$TanzuNetDevPassword"
        # pull registry for e2e tests that require a locally running docker registry. i.e. airgapped env tests
        docker pull registry:2

        ./hack/test-all.sh
